---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: vran-hornsby-app
  name: vran-hornsby-placemenrule
  namespace: hornsby
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'