---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: vran-cl9-app
  name: vran-cl9-placemenrule
  namespace: cl9
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'