---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: vran-cluster11-app
  name: vran-cluster11-subscription
  namespace: cluster11
spec:
  # channel: e2ecluster11clustergit-ns/e2ecluster11clustergit-channel
  channel: cluster11/e2ecluster11clustergit-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: vran-cluster11-placemenrule