---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: vran-cluster11-app
  name: vran-cluster11-placemenrule
  namespace: cluster11
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'