---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: vran-glebe-app
  name: vran-glebe-placemenrule
  namespace: glebe
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'