---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: vran-hornsby-app
  namespace: hornsby
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - vran-hornsby-app